config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :reviews

      resources :accounts

      resources :bookmarks

      resources :roles

      resources :actors

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :reviews
  resources :accounts
  resources :bookmarks
  resources :roles
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Direct associations

  has_many   :reviews,
             dependent: :destroy

  has_many   :bookmarks,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    username
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  def index
    @q = Account.ransack(params[:q])
    @accounts = @q.result(distinct: true).includes(:bookmarks,
                                                   :reviews).page(params[:page]).per(10)
  end

  def show
    @review = Review.new
    @bookmark = Bookmark.new
  end

  def new
    @account = Account.new
  end

  def edit; end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account, notice: "Account was successfully created."
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: "Account was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: "Account was successfully destroyed."
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:username, :email, :password)
  end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < Api::V1::GraphitiController
  def index
    accounts = AccountResource.all(params)
    respond_with(accounts)
  end

  def show
    account = AccountResource.find(params)
    respond_with(account)
  end

  def create
    account = AccountResource.build(params)

    if account.save
      render jsonapi: account, status: :created
    else
      render jsonapi_errors: account
    end
  end

  def update
    account = AccountResource.find(params)

    if account.update_attributes
      render jsonapi: account
    else
      render jsonapi_errors: account
    end
  end

  def destroy
    account = AccountResource.find(params)

    if account.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: account
    end
  end
end

app/views/accounts/_account_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#account_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @account.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="account_bookmarks_new_form">
        <%= render partial: "accounts/account_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/accounts/_account_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <%= f.hidden_field :account_id, value: @account.id %>

  <div class="form-group">
    <%= f.label :movie_id %>

    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/accounts/_account_reviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Reviews

    <a data-toggle="collapse" href="#account_reviews_new_form">
      Add review
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @account.reviews.each do |review| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to review, review %>

        <%= link_to review, method: :delete, data: { confirm: "Do you really want to delete this review" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="account_reviews_new_form">
        <%= render partial: "accounts/account_reviews_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/accounts/_account_reviews_new_form.html.erb
<%= form_with(model: @review, local: true) do |f| %>

  <%= f.hidden_field :account_id, value: @account.id %>

  <div class="form-group">
    <%= f.label :movie_id %>

    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>

    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <%= f.submit "Create review", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/accounts/_accounts_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "accounts_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :username_cont, "Username contains" %>
    <%= f.text_field :username_cont, :class => "form-control", :placeholder => "Username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :email_cont, "Email contains" %>
    <%= f.text_field :email_cont, :class => "form-control", :placeholder => "Email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/accounts" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#accounts_filters">
  Show filters
</a>

app/views/accounts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Account #<%= account.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Username</dt>
      <dd><%= account.username %></dd>

      <dt>Email</dt>
      <dd><%= account.email %></dd>

      <dt>Password</dt>
      <dd><%= account.password %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back account, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_account_url(account), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to account, method: :delete, data: { confirm: "Do you really want to delete this account?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(account.updated_at) %> ago
  </div>
</div>

app/views/accounts/_form.html.erb
<% was_validated = account.errors.any? %>

<%= form_with(model: account, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% username_class = "form-control" %>
    <% username_was_invalid = account.errors.include?(:username) %>

    <% if was_validated %>
      <% if username_was_invalid %>
        <% username_class << " is-invalid" %>
      <% else %>
        <% username_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :username %>
    <%= f.text_field :username, class: username_class, placeholder: "Enter username" %>
    <% if username_was_invalid %>
      <% account.errors.full_messages_for(:username).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% email_class = "form-control" %>
    <% email_was_invalid = account.errors.include?(:email) %>

    <% if was_validated %>
      <% if email_was_invalid %>
        <% email_class << " is-invalid" %>
      <% else %>
        <% email_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :email %>
    <%= f.text_field :email, class: email_class, placeholder: "Enter email" %>
    <% if email_was_invalid %>
      <% account.errors.full_messages_for(:email).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% password_class = "form-control" %>
    <% password_was_invalid = account.errors.include?(:password) %>

    <% if was_validated %>
      <% if password_was_invalid %>
        <% password_class << " is-invalid" %>
      <% else %>
        <% password_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :password %>
    <%= f.text_field :password, class: password_class, placeholder: "Enter password" %>
    <% if password_was_invalid %>
      <% account.errors.full_messages_for(:password).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/accounts/_list_item.html.erb
<%= link_to account, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= account %>
    <small class="text-muted">
      <%= time_ago_in_words(account.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/accounts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Account #<%= @account.id %>
      </h2>

      <div class="card-body">
        <%= render "form", account: @account %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Accounts

      <%= link_to new_account_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "accounts/accounts_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Accounts

        <%= link_to new_account_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @accounts, partial: "list_item", as: :account %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @accounts, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Account
      </h2>

      <div class="card-body">
        <%= render "form", account: @account %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @account, partial: "card", as: :account %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "accounts/account_bookmarks" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "accounts/account_reviews" %>
  </div>
</div>